local M = {}

function M.get(c, opts)
  return {
    ["@variable"]                    = { fg = c.fg },
    ["@variable.builtin"]            = { fg = c.cyan, italic = true },
    ["@variable.parameter"]          = { fg = c.fg_dim },
    ["@variable.member"]             = { fg = c.cyan },

    ["@constant"]                    = { fg = c.pink },
    ["@constant.builtin"]            = { fg = c.pink, bold = true },
    ["@constant.macro"]              = { fg = c.magenta },

    ["@module"]                      = { fg = c.cyan },
    ["@module.builtin"]              = { fg = c.cyan, bold = true },
    ["@label"]                       = { fg = c.yellow },

    ["@string"]                      = { fg = c.pink },
    ["@string.escape"]               = { fg = c.orange },
    ["@string.special"]              = { fg = c.orange },
    ["@string.special.symbol"]       = { fg = c.pink },
    ["@string.special.url"]          = { fg = c.blue, underline = true },
    ["@string.regexp"]               = { fg = c.orange },

    ["@character"]                   = { fg = c.pink },
    ["@character.special"]           = { fg = c.orange },

    ["@number"]                      = { fg = c.pink },
    ["@number.float"]                = { fg = c.pink },
    ["@boolean"]                     = { fg = c.pink, bold = opts.bold_keywords },

    ["@type"]                        = { fg = c.green },
    ["@type.builtin"]                = { fg = c.green, bold = opts.bold_keywords },
    ["@type.definition"]             = { fg = c.green },
    ["@type.qualifier"]              = { fg = c.yellow, bold = opts.bold_keywords },

    ["@attribute"]                   = { fg = c.magenta },
    ["@attribute.builtin"]           = { fg = c.magenta },
    ["@property"]                    = { fg = c.cyan },

    ["@function"]                    = { fg = c.cyan },
    ["@function.builtin"]            = { fg = c.cyan, bold = true },
    ["@function.call"]               = { fg = c.cyan },
    ["@function.macro"]              = { fg = c.magenta },
    ["@function.method"]             = { fg = c.cyan },
    ["@function.method.call"]        = { fg = c.cyan },

    ["@constructor"]                 = { fg = c.green },

    ["@keyword"]                     = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.coroutine"]           = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.function"]            = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.operator"]            = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.import"]              = { fg = c.magenta },
    ["@keyword.type"]                = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.modifier"]            = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.repeat"]              = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.return"]              = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.debug"]               = { fg = c.red },
    ["@keyword.exception"]           = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.conditional"]         = { fg = c.yellow, bold = opts.bold_keywords },
    ["@keyword.conditional.ternary"] = { fg = c.orange },
    ["@keyword.directive"]           = { fg = c.magenta },
    ["@keyword.directive.define"]    = { fg = c.magenta },

    ["@punctuation.delimiter"]       = { fg = c.fg_dim },
    ["@punctuation.bracket"]         = { fg = c.fg },
    ["@punctuation.special"]         = { fg = c.orange },

    ["@comment"]                     = { fg = c.blue, italic = opts.italic_comments },
    ["@comment.documentation"]       = { fg = c.blue, italic = opts.italic_comments },
    ["@comment.error"]               = { fg = c.red },
    ["@comment.warning"]             = { fg = c.gold },
    ["@comment.todo"]                = { fg = c.gold, bg = c.blue, bold = true },
    ["@comment.note"]                = { fg = c.cyan, bold = true },

    ["@markup.strong"]               = { bold = true },
    ["@markup.italic"]               = { italic = true },
    ["@markup.strikethrough"]        = { strikethrough = true },
    ["@markup.underline"]            = { underline = true },
    ["@markup.heading"]              = { fg = c.magenta, bold = true },
    ["@markup.heading.1"]            = { fg = c.magenta, bold = true },
    ["@markup.heading.2"]            = { fg = c.yellow, bold = true },
    ["@markup.heading.3"]            = { fg = c.cyan, bold = true },
    ["@markup.heading.4"]            = { fg = c.green, bold = true },
    ["@markup.heading.5"]            = { fg = c.orange },
    ["@markup.heading.6"]            = { fg = c.pink },
    ["@markup.quote"]                = { fg = c.fg_dark, italic = true },
    ["@markup.math"]                 = { fg = c.orange },
    ["@markup.link"]                 = { fg = c.blue, underline = true },
    ["@markup.link.label"]           = { fg = c.cyan },
    ["@markup.link.url"]             = { fg = c.blue, underline = true },
    ["@markup.raw"]                  = { fg = c.pink },
    ["@markup.raw.block"]            = { fg = c.pink },
    ["@markup.list"]                 = { fg = c.orange },
    ["@markup.list.checked"]         = { fg = c.green },
    ["@markup.list.unchecked"]       = { fg = c.fg_muted },

    ["@lsp.type.class"]              = { fg = c.green },
    ["@lsp.type.decorator"]          = { fg = c.magenta },
    ["@lsp.type.enum"]               = { fg = c.green },
    ["@lsp.type.enumMember"]         = { fg = c.pink },
    ["@lsp.type.function"]           = { fg = c.cyan },
    ["@lsp.type.interface"]          = { fg = c.teal },
    ["@lsp.type.keyword"]            = { fg = c.yellow, bold = opts.bold_keywords },
    ["@lsp.type.macro"]              = { fg = c.magenta },
    ["@lsp.type.method"]             = { fg = c.cyan },
    ["@lsp.type.namespace"]          = { fg = c.cyan },
    ["@lsp.type.number"]             = { fg = c.pink },
    ["@lsp.type.operator"]           = { fg = c.yellow },
    ["@lsp.type.parameter"]          = { fg = c.fg_dim },
    ["@lsp.type.property"]           = { fg = c.cyan },
    ["@lsp.type.regexp"]             = { fg = c.orange },
    ["@lsp.type.string"]             = { fg = c.pink },
    ["@lsp.type.struct"]             = { fg = c.green },
    ["@lsp.type.type"]               = { fg = c.green },
    ["@lsp.type.typeParameter"]      = { fg = c.teal },
    ["@lsp.type.variable"]           = { fg = c.fg },
    ["@lsp.mod.deprecated"]          = { strikethrough = true },
    ["@lsp.mod.readonly"]            = { italic = true },
  }
end

return M
